[font]
size = 15.0

[font.normal]
family = "Menlo"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
startup_mode = "Fullscreen"
option_as_alt = "OnlyRight"

[window.padding]
x = 16
y = 16

[colors.primary]
background = "0x000000"

[keyboard]
